### ISSUE TITLE
[BUG/ISSUE] shortcut menus acting weird

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#64] opened 2023-09-10 12:00 UTC
**Describe the bug**
title
**To Reproduce**
1. go to shortcuts
2. click on media and system keys
3. try to pick an option
![image](https://github.com/Paliverse/DSX/assets/92687769/5bcb93c6-df41-4b03-ab8c-6aee29c2046a)

**Comment by Paliverse** [comment] 2023-10-17 12:12
Duplicate of other posts

**Closed as completed by Paliverse** 2023-10-17 12:12 UTC
Labels: bug
