### ISSUE TITLE
[BUG/ISSUE] shortcut menus dissapearing

### ISSUE THREAD

**Issue by Execrit** [Paliverse/DSX#63] opened 2023-09-10 11:56 UTC
**Describe the bug**
title
**To Reproduce**
1. go to shortcuts
2. select a button
3. click on windows shortcut presets and start abusing the hell out of your scrolling wheel
![image](https://github.com/Paliverse/DSX/assets/92687769/69041d36-fdd7-49ea-9ba6-66abb8c937f8)

**Comment by Paliverse** [comment] 2023-10-17 12:12
Duplicate of other posts

**Closed as completed by Paliverse** 2023-10-17 12:12 UTC
Labels: bug
